config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ss_class.rb
class SsClass < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  EmailRegex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: EmailRegex },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "Hello, World"
  end

end

app/controllers/ss_classes_controller.rb
class SsClassesController < ApplicationController
  before_action :set_ss_class, only: [:show, :edit, :update, :destroy]

  # GET /ss_classes
  # GET /ss_classes.json
  def index
    @ss_classes = SsClass.all
  end

  # GET /ss_classes/1
  # GET /ss_classes/1.json
  def show
  end

  # GET /ss_classes/new
  def new
    @ss_class = SsClass.new
  end

  # GET /ss_classes/1/edit
  def edit
  end

  # POST /ss_classes
  # POST /ss_classes.json
  def create
    @ss_class = SsClass.new(ss_class_params)

    respond_to do |format|
      if @ss_class.save
        format.html { redirect_to @ss_class, notice: 'Ss class was successfully created.' }
        format.json { render :show, status: :created, location: @ss_class }
      else
        format.html { render :new }
        format.json { render json: @ss_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ss_classes/1
  # PATCH/PUT /ss_classes/1.json
  def update
    respond_to do |format|
      if @ss_class.update(ss_class_params)
        format.html { redirect_to @ss_class, notice: 'Ss class was successfully updated.' }
        format.json { render :show, status: :ok, location: @ss_class }
      else
        format.html { render :edit }
        format.json { render json: @ss_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ss_classes/1
  # DELETE /ss_classes/1.json
  def destroy
    @ss_class.destroy
    respond_to do |format|
      format.html { redirect_to ss_classes_url, notice: 'Ss class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ss_class
      @ss_class = SsClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ss_class_params
      params.require(:ss_class).permit(:name, :leader)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to RUMC Sunday Schools!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "RUMC Sunday School Resources"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/ss_classes_helper.rb
module SsClassesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80 )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The RUMC Sunday School App by Justin Collins
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Riverchase United Methodist Church", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>  
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/ss_classes/_form.html.erb
<%= form_with(model: ss_class, local: true) do |form| %>
  <% if ss_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ss_class.errors.count, "error") %> prohibited this ss_class from being saved:</h2>

      <ul>
      <% ss_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ss_class_name %>
  </div>

  <div class="field">
    <%= form.label :leader %>
    <%= form.text_field :leader, id: :ss_class_leader %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ss_classes/edit.html.erb
<h1>Editing Ss Class</h1>

<%= render 'form', ss_class: @ss_class %>

<%= link_to 'Show', @ss_class %> |
<%= link_to 'Back', ss_classes_path %>

app/views/ss_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ss Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Leader</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ss_classes.each do |ss_class| %>
      <tr>
        <td><%= ss_class.name %></td>
        <td><%= ss_class.leader %></td>
        <td><%= link_to 'Show', ss_class %></td>
        <td><%= link_to 'Edit', edit_ss_class_path(ss_class) %></td>
        <td><%= link_to 'Destroy', ss_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ss Class', new_ss_class_path %>

app/views/ss_classes/new.html.erb
<h1>New Ss Class</h1>

<%= render 'form', ss_class: @ss_class %>

<%= link_to 'Back', ss_classes_path %>

app/views/ss_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ss_class.name %>
</p>

<p>
  <strong>Leader:</strong>
  <%= @ss_class.leader %>
</p>

<%= link_to 'Edit', edit_ss_class_path(@ss_class) %> |
<%= link_to 'Back', ss_classes_path %>

app/views/static_pages/about.html.erb
    <h1>About</h1>
    <p>
      This site will be used to view and register for Riverchase United Methodist Sunday School Classes.
    </p>

app/views/static_pages/help.html.erb
  <p>
    Please contact the church for help.
  </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Riverchase United Methodist Church Sunday Schools</h1>

  <h2>
    This is the home page for the RUMC Sunday School App sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>